# Generated by Django 5.2.6 on 2025-09-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mpesarequest_mpesaresonse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesarequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.order'),
        ),
        migrations.CreateModel(
            name='MpesaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=10)),
                ('response_description', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=10)),
                ('customer_message', models.CharField(max_length=255)),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mpesarequest')),
            ],
        ),
        migrations.DeleteModel(
            name='MpesaResonse',
        ),
    ]
